services:
  01_pms_server_service:
    build: ./Server
    container_name: 01_pms_server_compose_container
    restart: always
    env_file:
      - ./Server/.env
    ports:
      - "4500:4500"

  01_pms_client_service:
    build:
      context: ./Client
      args:
        VITE_REACT_API_URL: http://16.112.189.21:4500
    container_name: 01_pms_client_compose_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - 01_pms_server_service
